services:
  openvpn:
    image: lisenet/openvpn:latest
    container_name: openvpn-server
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/openvpn:/etc/openvpn
    environment:
      - OVPN_SERVER=${OVPN_SERVER}
    restart: unless-stopped
